apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: database:5432
    database: octomind
    user: octomind
    secureJsonData:
      password: octomind_password
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    isDefault: true

  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: false

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: false 